/** Module settings: LLM + image generation providers, pipeline behavior. */

export const MODULE_ID = "acks-classic-importer";

export function registerSettings() {
  const S = (key, data) => game.settings.register(MODULE_ID, key, data);

  // ---- LLM provider ----
  S("llmProvider", {
    name: "LLM Provider",
    hint: "Provider used for structure extraction and conversion assistance.",
    scope: "world", config: true, type: String, default: "anthropic",
    choices: { anthropic: "Anthropic", openai: "OpenAI-compatible", custom: "Custom endpoint" }
  });
  S("llmEndpoint", {
    name: "LLM Endpoint URL",
    hint: "Leave blank to use the provider default. For custom/self-hosted, supply a full /v1/messages or /v1/chat/completions URL.",
    scope: "world", config: true, type: String, default: ""
  });
  S("llmApiKey", {
    name: "LLM API Key",
    scope: "world", config: true, type: String, default: ""
  });
  S("llmModel", {
    name: "LLM Model",
    hint: "e.g. claude-sonnet-4-5, gpt-4.1, or a local model name.",
    scope: "world", config: true, type: String, default: "claude-sonnet-4-5"
  });

  // ---- Image generation provider ----
  S("imgProvider", {
    name: "Image Generation Provider",
    scope: "world", config: true, type: String, default: "none",
    choices: {
      none: "None (programmatic maps, letter tokens)",
      comfyui: "ComfyUI (local)",
      openai: "OpenAI Images",
      stability: "Stability AI",
      custom: "Custom endpoint (POST, returns base64 PNG)"
    }
  });
  S("imgEndpoint", { name: "Image Endpoint URL", hint: "For ComfyUI this is the server root, e.g. http://127.0.0.1:8188", scope: "world", config: true, type: String, default: "" });
  S("imgApiKey",   { name: "Image API Key",      scope: "world", config: true, type: String, default: "" });
  S("imgModel",    { name: "Flux UNet / diffusion model filename", hint: "The Flux diffusion model (UNETLoader). Defaults to flux2-klein.safetensors. Overrides the Flux UNet setting below if both are set.", scope: "world", config: true, type: String, default: "flux2-klein.safetensors" });

  // ---- Flux 2 Klein loaders (built-in ComfyUI workflow) ----
  S("fluxUnet",  { name: "Flux UNet model",  hint: "Diffusion model for UNETLoader (e.g. flux2-klein.safetensors).", scope: "world", config: true, type: String, default: "flux2-klein.safetensors" });
  S("fluxClipL", { name: "Flux CLIP-L",      hint: "First CLIP for DualCLIPLoader (e.g. clip_l.safetensors).", scope: "world", config: true, type: String, default: "clip_l.safetensors" });
  S("fluxT5",    { name: "Flux T5 encoder",  hint: "Second CLIP/T5 for DualCLIPLoader (e.g. t5xxl_fp16.safetensors).", scope: "world", config: true, type: String, default: "t5xxl_fp16.safetensors" });
  S("fluxVae",   { name: "Flux VAE",         hint: "VAE for VAELoader (e.g. ae.safetensors).", scope: "world", config: true, type: String, default: "ae.safetensors" });
  S("mapDenoise", {
    name: "Map redraw strength (img2img denoise)",
    hint: "0.55–0.85. Maps are generated by handing Flux a labeled reference image and repainting it. Lower keeps the labeled layout more faithfully; higher repaints harder for a more finished look.",
    scope: "world", config: true, type: Number, default: 0.72,
    range: { min: 0.4, max: 0.9, step: 0.02 }
  });

  S("comfyWorkflow", {
    name: "ComfyUI workflow JSON (API format) — custom override",
    hint: "Leave blank to use the built-in Flux workflows (portrait txt2img; map img2img redraw of a labeled reference). Paste your own API-format workflow to override: placeholders %%PROMPT%%, %%NEGATIVE%%, %%WIDTH%%, %%HEIGHT%%, %%SEED%%, %%CHECKPOINT%%, %%INIT_IMAGE%% are substituted at run time.",
    scope: "world", config: true, type: String, default: ""
  });

  // ---- Pipeline behavior ----
  S("sourceEdition", {
    name: "Source edition",
    hint: "Which ruleset the PDF was written for. Auto-detect scores the text against stat-block conventions and logs its choice; override here if it guesses wrong.",
    scope: "world", config: true, type: String, default: "auto",
    choices: { auto: "Auto-detect", classic: "Classic (B/X, AD&D 1e/2e)", "5e": "5th Edition" }
  });
  S("generateTokenArt", {
    name: "Generate token/portrait art",
    hint: "If off (or provider is None), actors get generated letter-disc tokens.",
    scope: "world", config: true, type: Boolean, default: true
  });
  S("generateMapArt", {
    name: "Generate map backgrounds with the image model",
    hint: "If off, scenes use the deterministic line-map renderer (still fully walled and lit).",
    scope: "world", config: true, type: Boolean, default: false
  });
  S("reviewBeforeCreate", {
    name: "Review extracted data before creating documents",
    hint: "Strongly recommended. Shows the parsed JSON for each stage and lets you edit it before Foundry documents are created.",
    scope: "world", config: true, type: Boolean, default: true
  });
  S("gridSizePx", {
    name: "Scene grid size (px per square)",
    scope: "world", config: true, type: Number, default: 100
  });
  S("feetPerSquare", {
    name: "Feet per map square",
    hint: "Classic dungeon maps are usually 10' per square; wilderness/town maps vary and are read from the map key when possible.",
    scope: "world", config: true, type: Number, default: 10
  });
  S("itemCompendiums", {
    name: "Item compendium packs to check before creating gear",
    hint: "Comma-separated pack ids (e.g. 'acks.items,world.my-gear'). Matched items are linked instead of re-created; the importer's parsed bonuses/charges are merged in.",
    scope: "world", config: true, type: String, default: ""
  });
  S("encounterMapsPerTerrain", {
    name: "Tactical encounter maps per wilderness terrain type",
    hint: "When a hex/wilderness map is imported, generate this many square-grid 'zoom-in' battle maps for each distinct terrain type found (forest, hills, swamp…), with obstacle walls placed. 0 disables.",
    scope: "world", config: true, type: Number, default: 1,
    range: { min: 0, max: 2, step: 1 }
  });
  S("monsterCompendiums", {
    name: "Monster compendium packs to check before creating",
    hint: "Comma-separated pack ids (e.g. 'acks.monsters,world.my-bestiary'). The importer's own 'imported-monsters' pack is always checked.",
    scope: "world", config: true, type: String, default: ""
  });
}

export function getSetting(key) {
  return game.settings.get(MODULE_ID, key);
}
